In [9]:
#Import libraries
import pandas as pd

In [11]:
#Read the parquet file
compliments_df = pd.read_parquet('../data/raw/compliments.parquet')

In [13]:
#Find the first 10 rows of the dataset
compliments_df.head(10)

,brands_tags,brands,code,countries_tags,images,ingredients_original_tags,ingredients_tags,ingredients,nutriments,product_name,product_quantity_unit,product_quantity,quantity,traces_tags,vitamins_tags
0,[xx:compliments],Compliments,0055742346022,"[en:canada, en:france]","[{'key': '4', 'imgid': None, 'rev': None, 'siz...","[en:crust, en:filling, en:fortified-wheat-flou...","[en:crust, en:filling, en:fortified-wheat-flou...","[{""percent_max"":100.0,""percent_min"":50.0,""is_i...","[{'name': 'added-sugars', 'value': None, '100g...","[{'lang': 'main', 'text': 'Strawberry Cereal B...",g,300.0,300 g,[en:eggs],[]
1,[xx:compliments],Compliments,0055742348279,[en:canada],"[{'key': '9', 'imgid': None, 'rev': None, 'siz...","[en:peanut, en:sugar, en:hydrogenated-vegetabl...","[en:peanut, en:nut, en:sugar, en:added-sugar, ...","[{""percent_max"":100.0,""percent_min"":93.9,""is_i...","[{'name': 'saturated-fat', 'value': None, '100...","[{'lang': 'main', 'text': 'Smooth Peanut Butte...",g,500.0,500 g,[en:nuts],[]
2,[xx:compliments],Compliments,0055742350500,[en:france],"[{'key': '3', 'imgid': None, 'rev': None, 'siz...","[en:peanut, fr:sucre-a-glacer, en:hydrogenated...","[en:peanut, en:nut, fr:sucre-a-glacer, en:hydr...","[{""percent_max"":100.0,""percent_min"":20.0,""is_i...","[{'name': 'energy', 'value': None, '100g': 270...","[{'lang': 'main', 'text': 'Beurre d'arachide (...",None,None,,[],[]
3,[xx:compliments],Compliments,0055742357912,"[en:canada, en:france]","[{'key': '3', 'imgid': None, 'rev': None, 'siz...","[en:durum-wheat-semolina, en:e375, en:ferrous-...","[en:durum-wheat-semolina, en:cereal, en:wheat,...","[{""percent_max"":100.0,""percent_min"":16.6666666...","[{'name': 'added-sugars', 'value': None, '100g...","[{'lang': 'main', 'text': 'Fettucine'}, {'lang...",g,900.0,900g,[],"[en:niacin, en:riboflavin, en:thiamin-mononitr..."
4,[xx:compliments],Compliments,0055742358988,[en:france],"[{'key': '3', 'imgid': None, 'rev': None, 'siz...",None,None,None,"[{'name': 'saturated-fat', 'value': None, '100...","[{'lang': 'main', 'text': 'Melasse'}, {'lang':...",None,None,None,[],[]
5,[xx:compliments],Compliments,0055742359886,[en:france],"[{'key': '1', 'imgid': None, 'rev': None, 'siz...","[fr:not-a-significant-source-of-saturated-fat,...","[fr:not-a-significant-source-of-saturated-fat,...","[{""percent_max"":100.0,""percent_min"":6.25,""is_i...","[{'name': 'added-sugars', 'value': None, '100g...","[{'lang': 'main', 'text': 'Persil Déshydraté E...",None,None,None,[],[en:vitamin-a]
6,[xx:compliments],Compliments,0055742363425,[en:canada],"[{'key': '1', 'imgid': None, 'rev': None, 'siz...",None,None,None,"[{'name': 'salt', 'value': None, '100g': 0.620...","[{'lang': 'main', 'text': 'Crushed tomatoes'},...",ml,796.0,796 mL,[],[]
7,[xx:compliments],Compliments,0055742366891,[en:france],"[{'key': '1', 'imgid': None, 'rev': None, 'siz...",[en:honey],"[en:honey, en:added-sugar]","[{""percent_max"":100.0,""percent_min"":100.0,""is_...","[{'name': 'galactose', 'value': None, '100g': ...","[{'lang': 'main', 'text': 'Miel biologique pur...",g,500,500 g,[],[]
8,[xx:compliments],Compliments,0055742367164,[en:france],"[{'key': '4', 'imgid': None, 'rev': None, 'siz...",[fr:peanuts],[fr:peanuts],"[{""percent_max"":100.0,""percent_min"":100.0,""is_...","[{'name': 'fat', 'value': None, '100g': 46.666...","[{'lang': 'main', 'text': 'Natural crunchy pea...",None,None,None,[],[]
9,[xx:compliments],Compliments,0055742369212,[en:canada],"[{'key': '4', 'imgid': None, 'rev': None, 'siz...",[en:date],"[en:date, en:fruit]","[{""percent_max"":100.0,""percent_min"":100.0,""is_...","[{'name': 'beta-carotene', 'value': None, '100...","[{'lang': 'main', 'text': 'Pitted dates'}, {'l...",g,600,600g,[],[]

In [15]:
#Find the number of null values for each column
compliments_df.isnull().sum()

brands_tags                     0
brands                          0
code                            0
countries_tags                  6
images                          0
ingredients_original_tags    1363
ingredients_tags             1363
ingredients                  1363
nutriments                     77
product_name                    0
product_quantity_unit        1389
product_quantity             1376
quantity                     1324
traces_tags                     0
vitamins_tags                1220
dtype: int64

In [21]:
#Get the columns in the dataset
compliments_df.columns

Index(['brands_tags', 'brands', 'code', 'countries_tags', 'images',
       'ingredients_original_tags', 'ingredients_tags', 'ingredients',
       'nutriments', 'product_name', 'product_quantity_unit',
       'product_quantity', 'quantity', 'traces_tags', 'vitamins_tags'],
      dtype='object')

In [65]:
#Find the number of rows and columns in the dataset
compliments_df.shape

(1835, 15)

In [27]:
#Find the datatype of each column in the dataset
for i in compliments_df.columns:
    print(compliments_df[i].dtype)

object
object
object
object
object
object
object
object
object
object
object
object
object
object
object

In [31]:
#Since brands_tags itself is like an array, explode() has been used to flatten and obtain the unique values
compliments_df['brands_tags'].explode().unique()

array(['xx:compliments', 'compliments', 'xx:Compliments'], dtype=object)

In [43]:
compliments_df['brands_tags'].iloc[0]

array(['xx:compliments'], dtype=object)

In [47]:
#Obtain rows which matches brands_tags exactly with 'compliments'
compliments_only = compliments_df[compliments_df['brands_tags'].apply(lambda x: len(x) == 1 and x[0] == 'compliments')]
len(compliments_only)

113

In [51]:
#Obtain those products where the brand name was mentioned as 'compliments'
compliments_only[['brands_tags', 'product_name']]

        brands_tags                                       product_name
11    [compliments]  [{'lang': 'main', 'text': 'Brown Rice'}, {'lan...
15    [compliments]  [{'lang': 'main', 'text': 'Craquelins de blé m...
18    [compliments]  [{'lang': 'main', 'text': 'Gluten-Free Crisp R...
44    [compliments]  [{'lang': 'main', 'text': 'Quick oats'}, {'lan...
52    [compliments]  [{'lang': 'main', 'text': 'Medium Cheddar'}, {...
...             ...                                                ...
1411  [compliments]  [{'lang': 'main', 'text': 'Mild pepperoni'}, {...
1419  [compliments]  [{'lang': 'main', 'text': 'English Muffins'}, ...
1425  [compliments]  [{'lang': 'main', 'text': 'Bacon entièrement c...
1438  [compliments]  [{'lang': 'main', 'text': 'Crevettes'}, {'lang...
1541  [compliments]  [{'lang': 'main', 'text': 'Wheat Crackers'}, {...

[113 rows x 2 columns]

In [59]:
#Obtain the brands_tags and product_name from the dataset where the countries_tags is null
compliments_df.loc[compliments_df['countries_tags'].isnull(), ['brands_tags', 'product_name']]

           brands_tags                                       product_name
240      [compliments]  [{'lang': 'main', 'text': 'Prepared horseradis...
429      [compliments]  [{'lang': 'main', 'text': 'Whole Wheat Naan Ro...
1273  [xx:compliments]  [{'lang': 'main', 'text': 'Granulated Sweetene...
1283  [xx:compliments]  [{'lang': 'main', 'text': 'Cottage Cheese Dry ...
1285  [xx:compliments]  [{'lang': 'main', 'text': 'Lean Ground Pork'},...
1288     [compliments]  [{'lang': 'main', 'text': 'Fruity Hoops'}, {'l...

In [63]:
compliments_df['product_name'].dtype

dtype('O')

In [67]:
# Obtain the exact product name from 'main' language
def get_main_product_name(prod_name):
    if prod_name is None:
        return None
    for item in prod_name:
        if item['lang'] == 'main':
            return item['text']
    return None

In [71]:
# Obtain the exact product name from 'main' language where countries_tags is null
null_countries_products = compliments_df.loc[compliments_df['countries_tags'].isnull(), 'product_name'].apply(get_main_product_name)
null_countries_products

240                    Prepared horseradish
429                 Whole Wheat Naan Rounds
1273    Granulated Sweetener With Sucralose
1283                Cottage Cheese Dry Curd
1285                       Lean Ground Pork
1288                           Fruity Hoops
Name: product_name, dtype: object

In [33]:
#Find the unique values of countries_tags
compliments_df['countries_tags'].explode().unique()

array(['en:canada', 'en:france', 'en:saint-pierre-and-miquelon',
       'en:united-states', nan, None, 'en:germany', 'en:italy',
       'en:ireland', 'en:switzerland', 'en:austria', 'en:united-kingdom',
       'en:japan'], dtype=object)

In [75]:
compliments_df[compliments_df['product_quantity_unit'].isnull() & compliments_df['product_quantity'].isnull() & compliments_df['quantity'].notnull()]

,brands_tags,brands,code,countries_tags,images,ingredients_original_tags,ingredients_tags,ingredients,nutriments,product_name,product_quantity_unit,product_quantity,quantity,traces_tags,vitamins_tags
2,[xx:compliments],Compliments,0055742350500,[en:france],"[{'key': '3', 'imgid': None, 'rev': None, 'siz...","[en:peanut, fr:sucre-a-glacer, en:hydrogenated...","[en:peanut, en:nut, fr:sucre-a-glacer, en:hydr...","[{""percent_max"":100.0,""percent_min"":20.0,""is_i...","[{'name': 'energy', 'value': None, '100g': 270...","[{'lang': 'main', 'text': 'Beurre d'arachide (...",None,None,,[],[]
11,[compliments],Compliments,0055742373561,[en:canada],"[{'key': 'ingredients_fr', 'imgid': 1.0, 'rev'...",None,None,None,None,"[{'lang': 'main', 'text': 'Brown Rice'}, {'lan...",None,None,,[],[]
17,[xx:compliments],Compliments,0055742500486,[en:france],"[{'key': '1', 'imgid': None, 'rev': None, 'siz...",None,None,None,"[{'name': 'proteins', 'value': None, '100g': 1...","[{'lang': 'main', 'text': 'Farine sans gluten'...",None,None,,[],[]
26,[xx:compliments],Compliments,0055742508925,[en:france],"[{'key': '2', 'imgid': None, 'rev': None, 'siz...",[en:long-grain-rice],"[en:long-grain-rice, en:rice]","[{""percent_max"":100.0,""percent_min"":100.0,""is_...","[{'name': 'energy', 'value': None, '100g': 148...","[{'lang': 'main', 'text': 'Riz à grain long'},...",None,None,,[],[]
55,[xx:compliments],Compliments,0068820121701,[en:france],"[{'key': '3', 'imgid': None, 'rev': None, 'siz...","[fr:poulet-separe-mecaniquement, en:wheat-flou...","[fr:poulet-separe-mecaniquement, en:wheat-flou...","[{""percent_max"":100.0,""percent_min"":6.66666666...","[{'name': 'added-sugars', 'value': None, '100g...","[{'lang': 'main', 'text': 'Saucisses fumees au...",None,None,,[],[]
58,[xx:compliments],Compliments,0623682103588,[en:france],"[{'key': '1', 'imgid': None, 'rev': None, 'siz...",None,None,None,"[{'name': 'salt', 'value': None, '100g': 0.0, ...","[{'lang': 'main', 'text': 'Jus D'orange (sans ...",None,None,,[],[]
59,[xx:compliments],Compliments,0623682105766,[en:france],"[{'key': '1', 'imgid': None, 'rev': None, 'siz...",None,None,None,"[{'name': 'salt', 'value': None, '100g': 0.020...","[{'lang': 'main', 'text': 'Sirop D'erable Pur'...",None,None,,[],[]
63,[xx:compliments],Compliments,0055742528404,[en:france],"[{'key': '1', 'imgid': None, 'rev': None, 'siz...","[en:fortified-wheat-flour, en:oat-flakes, en:p...","[en:fortified-wheat-flour, en:cereal, en:flour...","[{""percent_max"":100.0,""percent_min"":6.66666666...","[{'name': 'pantothenic-acid', 'value': None, '...","[{'lang': 'main', 'text': 'Oatmeal chocolate c...",None,None,,[],[]
97,[xx:compliments],Compliments,0055742357509,"[en:canada, en:france]","[{'key': '2', 'imgid': None, 'rev': None, 'siz...",[en:large-chicken-eggs],[en:large-chicken-eggs],"[{""percent_max"":100.0,""percent_min"":100.0,""is_...","[{'name': 'fruits-vegetables-nuts', 'value': N...","[{'lang': 'en', 'text': 'Large white eggs'}, {...",None,None,12 pcs,[],[]
116,[xx:compliments],Compliments,0055742371314,[en:canada],"[{'key': '1', 'imgid': None, 'rev': None, 'siz...","[fr:corn-starch, fr:carrot, fr:canola-oil, fr:...","[fr:corn-starch, fr:carrot, fr:canola-oil, fr:...","[{""percent_max"":100.0,""percent_min"":2.85714285...","[{'name': 'energy-kcal', 'value': None, '100g'...","[{'lang': 'main', 'text': 'Lasagnes'}, {'lang'...",None,None,,[],[]
142,[xx:compliments],Compliments,0055742545753,[en:canada],"[{'key': '1', 'imgid': None, 'rev': None, 'siz...",None,None,None,None,"[{'lang': 'main', 'text': 'Ketchup'}, {'lang':...",None,None,,[],[]
151,[xx:compliments],Compliments,0055742552447,[en:canada],"[{'key': '2', 'imgid': None, 'rev': None, 'siz...","[en:apple, en:water, en:e300]","[en:apple, en:fruit, en:malaceous-fruit, en:wa...","[{""percent_max"":100.0,""percent_min"":33.3333333...","[{'name': 'fruits-vegetables-nuts', 'value': N...","[{'lang': 'main', 'text': 'Apple Sauce'}, {'la...",None,None,,[],[en:l-ascorbic-acid]
157,[xx:compliments],Compliments,0055742374629,[en:canada],"[{'key': '3', 'imgid': None, 'rev': None, 'siz...","[en:water, en:tomato-concentrate, en:salt, en:...","[en:water, en:tomato-concentrate, en:vegetable...","[{""percent_max"":100.0,""percent_min"":47.0,""is_i...","[{'name': 'energy-kcal', 'value': None, '100g'...",[],None,None,,[],[]
169,[xx:compliments],Compliments,0055742512588,[en:canada],"[{'key': '2', 'imgid': None, 'rev': None, 'siz...",[en:orange],"[en:orange, en:fruit, en:citrus-fruit]","[{""percent_max"":100.0,""percent_min"":100.0,""is_...","[{'name': 'starch', 'value': None, '100g': 0.1...","[{'lang': 'main', 'text': 'Jus d'orange pur 10...",None,None,,[],[]
191,[xx:compliments],Compliments,0068820107255,[en:canada],"[{'key': '1', 'imgid': None, 'rev': None, 'siz...",None,None,None,"[{'name': 'carbohydrates', 'value': None, '100...","[{'lang': 'main', 'text': 'Apple gala'}, {'lan...",None,None,,[],[]
225,[xx:compliments],Compliments,0055742552362,[en:canada],"[{'key': '2', 'imgid': None, 'rev': None, 'siz...",None,None,None,"[{'name': 'proteins', 'value': None, '100g': 1...","[{'lang': 'main', 'text': 'Mayonnaise chipotle...",None,None,,[],None
226,[xx:compliments],Compliments,0055742550252,[en:canada],"[{'key': '4', 'imgid': None, 'rev': None, 'siz...",None,None,None,"[{'name': 'fat', 'value': None, '100g': 26.0, ...","[{'lang': 'main', 'text': 'Zesty taco flavoure...",None,None,1,[],None
233,[xx:compliments],Compliments,0055742550498,[en:canada],"[{'key': '7', 'imgid': None, 'rev': None, 'siz...","[en:ultrafiltered-skim, en:milk-skim-milk-bact...","[en:ultrafiltered-skim, en:milk-skim-milk-bact...","[{""percent_max"":100.0,""percent_min"":25.0,""is_i...","[{'name': 'choline', 'value': None, '100g': 0....","[{'lang': 'main', 'text': 'Greek Plain'}, {'la...",None,None,,[],"[en:retinyl-palmitate, en:cholecalciferol]"
236,[xx:compliments],Compliments,0068820133674,[en:canada],"[{'key': '3', 'imgid': None, 'rev': None, 'siz...","[en:turkey-breast, en:water, en:sugar, en:modi...","[en:turkey-breast, en:poultry, en:turkey, en:t...","[{""percent_max"":100.0,""percent_min"":50.0,""is_i...","[{'name': 'fiber', 'value': None, '100g': 0.0,...","[{'lang': 'main', 'text': 'Herb Turkey Breast ...",None,None,,[en:eggs],[]
238,[compliments],Compliments,0055742550573,[],"[{'key': '1', 'imgid': None, 'rev': None, 'siz...","[en:breadcrumbs, en:sugar, en:wheat, en:malted...","[en:breadcrumbs, en:coating, en:sugar, en:adde...","[{""percent_max"":null,""percent_min"":null,""is_in...","[{'name': 'carbohydrates', 'value': 75.0, '100...","[{'lang': 'main', 'text': 'Original coating mi...",None,None,,[],[]
307,[xx:compliments],Compliments,0055742521917,[en:france],"[{'key': '1', 'imgid': None, 'rev': None, 'siz...","[en:black-bean, en:water, en:e509]","[en:black-bean, en:vegetable, en:legume, en:pu...","[{""percent_max"":100.0,""percent_min"":33.3333333...","[{'name': 'calcium', 'value': None, '100g': 0....","[{'lang': 'main', 'text': 'Black Beans'}, {'la...",None,None,,[],[]
326,[xx:compliments],Compliments,0055742562811,[en:canada],"[{'key': '1', 'imgid': None, 'rev': None, 'siz...",None,None,None,"[{'name': 'saturated-fat', 'value': None, '100...","[{'lang': 'main', 'text': 'Tranche fromage jau...",None,None,,[],[]
339,[xx:compliments],Compliments,0055742551488,[en:canada],"[{'key': '2', 'imgid': None, 'rev': None, 'siz...","[en:popcorn, en:oil, en:salt]","[en:popcorn, en:cereal, en:corn, en:oil, en:oi...","[{""percent_max"":100.0,""percent_min"":49.475,""is...","[{'name': 'fruits-vegetables-legumes', 'value'...","[{'lang': 'main', 'text': 'Pop simple'}, {'lan...",None,None,,[],[]
404,[xx:compliments],Compliments,0055742357561,[en:canada],"[{'key': '2', 'imgid': None, 'rev': None, 'siz...",[en:large-chicken-eggs],[en:large-chicken-eggs],"[{""percent_max"":100.0,""percent_min"":100.0,""is_...","[{'name': 'saturated-fat', 'value': None, '100...","[{'lang': 'main', 'text': 'Large eggs'}, {'lan...",None,None,"12 eggs, Net: g",[],[]
442,[xx:compliments],Compliments,0055742556469,[en:canada],"[{'key': '1', 'imgid': None, 'rev': None, 'siz...",None,None,None,"[{'name': 'salt', 'value': None, '100g': 0.152...","[{'lang': 'main', 'text': 'yogourt glacé'}, {'...",None,None,,[],[]
471,[xx:compliments],Compliments,0068820134527,[en:canada],"[{'key': '2', 'imgid': None, 'rev': None, 'siz...","[en:water, en:sugar, en:whole-wheat-flour, en:...","[en:water, en:sugar, en:added-sugar, en:disacc...","[{""percent_max"":100.0,""percent_min"":7.69230769...","[{'name': 'polyols', 'value': None, '100g': 0....","[{'lang': 'main', 'text': 'Raisins secs et son...",None,None,6 per container,"[en:milk, en:nuts, en:sesame-seeds]",[]
477,[xx:compliments],Compliments,0055742560862,[en:canada],"[{'key': '2', 'imgid': None, 'rev': None, 'siz...","[en:oat, en:sugar, en:wheat-flakes, en:coconut...","[en:oat, en:cereal, en:sugar, en:added-sugar, ...","[{""percent_max"":100.0,""percent_min"":10.0,""is_i...","[{'name': 'calcium', 'value': None, '100g': 0....","[{'lang': 'main', 'text': 'Chocolate Almond Gr...",None,None,,[en:nuts],[]
507,[xx:compliments],Compliments,0055742563573,[en:canada],"[{'key': '2', 'imgid': None, 'rev': None, 'siz...",None,None,None,"[{'name': 'sodium', 'value': None, '100g': 0.1...","[{'lang': 'main', 'text': 'Eggs'}, {'lang': 'f...",None,None,30 pcs,[],None
513,[xx:compliments],Compliments,0055742558968,[en:canada],"[{'key': '4', 'imgid': None, 'rev': None, 'siz...",None,None,None,"[{'name': 'saturated-fat', 'value': None, '100...","[{'lang': 'main', 'text': 'Vegetable Samosas'}...",None,None,,[],[]
539,[xx:compliments],Compliments,0055742502749,[en:canada],"[{'key': '3', 'imgid': None, 'rev': None, 'siz...","[en:cornmeal, en:canola, en:sunflower-oil, en:...","[en:cornmeal, en:cereal, en:corn, en:canola, e...","[{""percent_max"":100.0,""percent_min"":25.0,""is_i...","[{'name': 'salt', 'value': None, '100g': 1.600...","[{'lang': 'main', 'text': 'Cheese Sticks'}, {'...",None,None,,[],[]
547,[xx:compliments],Compliments,0055742552195,[en:canada],"[{'key': '2', 'imgid': None, 'rev': None, 'siz...",None,None,None,"[{'name': 'carbohydrates', 'value': None, '100...","[{'lang': 'main', 'text': 'Crinkle Cut Low Sod...",None,None,,[],[]
580,[xx:compliments],Compliments,9033802357998,[en:canada],"[{'key': '2', 'imgid': None, 'rev': None, 'siz...",None,None,None,"[{'name': 'sugars', 'value': None, '100g': 3.5...","[{'lang': 'main', 'text': 'Rotini'}, {'lang': ...",None,None,,[],[]
596,[xx:compliments],Compliments,0068820133391,[en:canada],"[{'key': '2', 'imgid': None, 'rev': None, 'siz...","[en:apple, en:salt, en:sugar, en:water, en:mod...","[en:apple, en:fruit, en:malaceous-fruit, en:sa...","[{""percent_max"":100.0,""percent_min"":96.6554054...","[{'name': 'phylloquinone', 'value': None, '100...","[{'lang': 'main', 'text': 'Apple pie'}, {'lang...",None,None,,[],[]
613,[xx:compliments],Compliments,0055742526134,[en:canada],"[{'key': '2', 'imgid': None, 'rev': None, 'siz...",None,None,None,"[{'name': 'fiber', 'value': None, '100g': 0.0,...","[{'lang': 'main', 'text': 'Lait de coco'}, {'l...",None,None,400,[],None
626,[xx:compliments],Compliments,0055742563580,[en:canada],"[{'key': '4', 'imgid': None, 'rev': None, 'siz...",[en:large-chicken-eggs],[en:large-chicken-eggs],"[{""percent_max"":100.0,""percent_min"":100.0,""is_...","[{'name': 'vitamin-d', 'value': None, '100g': ...","[{'lang': 'main', 'text': 'Eggs value size'}, ...",None,None,"30 Lg eggs, Net: g.",[],[]
686,[xx:compliments],Compliments,0068820129301,[en:united-states],"[{'key': '1', 'imgid': None, 'rev': None, 'siz...",None,None,None,"[{'name': 'trans-fat', 'value': None, '100g': ...","[{'lang': 'main', 'text': 'Bacon-Style Turkey'...",None,None,2,[],None
691,[xx:compliments],Compliments,0055742557053,[en:canada],"[{'key': '3', 'imgid': None, 'rev': None, 'siz...",None,None,None,"[{'name': 'sodium', 'value': None, '100g': 0.0...","[{'lang': 'main', 'text': 'Jelly Bean Hearts'}...",None,None,,[],[]
692,[xx:compliments],Compliments,0055742566185,[en:canada],"[{'key': '1', 'imgid': None, 'rev': None, 'siz...","[en:apple, en:glucose-fructose, en:water, fr:a...","[en:apple, en:fruit, en:malaceous-fruit, en:gl...","[{""percent_max"":100.0,""percent_min"":25.0,""is_i...","[{'name': 'fruits-vegetables-nuts', 'value': N...","[{'lang': 'main', 'text': 'Purée de pommes'}, ...",None,None,,[],[]
706,[xx:compliments],Compliments,0055742360325,[en:canada],"[{'key': '2', 'imgid': None, 'rev': None, 'siz...",None,None,None,"[{'name': 'iron', 'value': None, '100g': 0.000...","[{'lang': 'main', 'text': 'Whole Kernel Corn'}...",None,None,,[],[]
742,[xx:compliments],Compliments,0055742560190,[en:canada],"[{'key': '1', 'imgid': None, 'rev': None, 'siz...",None,None,None,"[{'name': 'sodium', 'value': None, '100g': 0.0...","[{'lang': 'main', 'text': 'Mini Strawberry Fro...",None,None,,[],[]
757,[xx:compliments],Compliments,0068820135494,[en:canada],"[{'key': '1', 'imgid': None, 'rev': None, 'siz...",None,None,None,"[{'name': 'carbohydrates', 'value': None, '100...","[{'lang': 'main', 'text': 'Baby Spinach'}, {'l...",None,None,,[],[]
781,[xx:compliments],Compliments,0055742558746,[en:canada],"[{'key': '2', 'imgid': None, 'rev': None, 'siz...",None,None,None,"[{'name': 'energy', 'value': None, '100g': 186...","[{'lang': 'main', 'text': 'Cluck Wing Sauce Fu...",None,None,,[],None
789,[compliments],Compliments,0055742509373,[en:canada],[],None,None,None,None,"[{'lang': 'main', 'text': 'Sacs à collations'}...",None,None,75,[],None
800,[xx:compliments],Compliments,0055742568912,"[en:canada, en:united-states]","[{'key': '2', 'imgid': None, 'rev': None, 'siz...",[en:large-free-run-omega-3-eggs],[en:large-free-run-omega-3-eggs],"[{""percent_max"":100.0,""percent_min"":100.0,""is_...","[{'name': 'fiber', 'value': None, '100g': 0.0,...","[{'lang': 'main', 'text': '12 Omega-3 Free-Run...",None,None,"12 eggs, Net: g",[],[]
802,[xx:compliments],Compliments,05578016,[en:united-states],"[{'key': '1', 'imgid': None, 'rev': None, 'siz...",None,None,None,"[{'name': 'fiber', 'value': 11.0, '100g': 36.7...","[{'lang': 'main', 'text': 'Chia seeds'}, {'lan...",None,None,,[],[]
838,[xx:compliments],Compliments,0055742549218,[en:canada],"[{'key': '4', 'imgid': None, 'rev': None, 'siz...",None,None,None,"[{'name': 'sugars', 'value': None, '100g': 4.0...","[{'lang': 'main', 'text': 'Bacon and Chedder'}...",None,None,,[],[]
890,[xx:compliments],Compliments,0055742555073,[en:canada],"[{'key': '4', 'imgid': None, 'rev': None, 'siz...",[en:mono-and-diglycerides-xanthan-gum-carob-be...,[en:mono-and-diglycerides-xanthan-gum-carob-be...,"[{""percent_max"":100.0,""percent_min"":16.6666666...","[{'name': 'salt', 'value': None, '100g': 0.579...","[{'lang': 'main', 'text': 'Cottage Cheese'}, {...",None,None,,[],[]
922,[xx:compliments],Compliments,0055742569865,[en:canada],"[{'key': '2', 'imgid': None, 'rev': None, 'siz...",None,None,None,"[{'name': 'sugars', 'value': None, '100g': 0.0...","[{'lang': 'main', 'text': 'Oeufs brun calibre ...",None,None,12 pcs,[],None
1037,[xx:compliments],Compliments,0055742564358,[en:canada],"[{'key': '3', 'imgid': None, 'rev': None, 'siz...",None,None,None,"[{'name': 'fat', 'value': None, '100g': 90.0, ...","[{'lang': 'main', 'text': 'Compliments'}, {'la...",None,None,,[],None
1105,[xx:compliments],Compliments,0055742551983,[en:canada],"[{'key': '1', 'imgid': None, 'rev': None, 'siz...",None,None,None,"[{'name': 'fiber', 'value': None, '100g': 6.0,...","[{'lang': 'main', 'text': 'Peanut jalapeino'},...",None,None,,[],None
1537,[xx:compliments],Compliments,0055742357943,[en:canada],"[{'key': '2', 'imgid': None, 'rev': None, 'siz...",None,None,None,"[{'name': 'starch', 'value': None, '100g': 0.0...","[{'lang': 'main', 'text': 'Lasagna'}, {'lang':...",None,None,,[],None
1675,[xx:compliments],Compliments,0055742511086,[en:canada],"[{'key': '1', 'imgid': None, 'rev': None, 'siz...","[en:carottes-tranchees, en:haricots-romains, e...","[en:carottes-tranchees, en:haricots-romains, e...","[{""percent_max"":100.0,""percent_min"":20.0,""is_i...","[{'name': 'energy-kcal', 'value': None, '100g'...","[{'lang': 'main', 'text': 'Italian Style Veget...",None,None,,[],[]

In [77]:
compliments_df['quantity'].unique()

array(['300 g', '500 g', '', '900g', None, '796 mL', '600g', '350 g',
       '341 ml', '398 mL', '250g', '6 x 113 g', '350g', '170g', '500 mL',
       '1 L', '398 ml', '408 g', '336 g', '200 ml', '48 mL', '946 ml',
       '1 kg', '2.25kg', '200 g', '170 g', '4,54 kg', '210 g', '227g',
       '700 ml', '280g', '360g', '1,5 l', '225g', '300g', '300 ml',
       '284 mL', '1kg', '100g', '490 g', '540 gr', '280 g', '320gr',
       '400g', '12 pcs', '10g', '225 g', '200g', '2kg', '400 grammes',
       '375 ml', '284 ml', '450 g', '675 g', '473 mL', '340mL', '355 mL',
       '145 g', '375 mL', '340 g', '6 x 113 g,  678 g', '540 mL', '100 g',
       '10 Tortillas, 610 g', '2 L', '890 mL', '6x 75 g,  Net: 450 g',
       '454 g', '85 g', '250 g', '40 g', '8 x 142 g', '1.5 L', '946 mL',
       '1', '454g', '2.5 kg', '6 x 170 g', '2 kg', '750g', '390g',
       '900 mL', '16 rounds, 480 g.', '650 mL', '503 mL', '6 x 6 oz',
       '700 g', '473 ml', '12 x 90 g', '3 x 80 g', '342 g /  6 portions',
       '430ml', '360 g', '50g', '325 mL', '410 g', '6 x 80 ml',
       '6 x 75 ml', '1.75 L', '120 g', '325 g', '2 flatbreads, 220 grams',
       '445 mL', '12 eggs,  Net:     g', '750 mL', '250 mL', '428 ml',
       '4 x 100 g', '156 g', '1.54 L', '6 x 113 g  Net: 678 g', '475 mL',
       '375 g', '900 g', '1.65 L', '6 per container', '30 pcs',
       '12 x 110 ml', '125 g', '1.81 kg', '12 x 60 ml', '60 g', '620ml',
       '710 mL', '200 mL', '1.89 L', '1256 g / 48 barres', '400 g',
       '255 g', '325g', '4x99g', '227 g', '12 x 50 ml', '175 g', '540 g',
       '1.13kg', '570 g', '400', '500g', '1.13 kg', '755 g',
       '30 Lg eggs,  Net:     g.', '350 ml', '638 g', '425 mL', '87 g',
       '275 g', '2', '320 g', '2.27 kg', '350 mL', '1.8 kg', '685 g',
       '500 ml', '400 mL', '20 g', '400 ml', '6 x 142 g', '1.4 kg', '75',
       '580 mL', '3 L', '185 mL', '390 g', '680 mL', '8 x 55 ml',
       '10 x 80 g', '907 g', '270 g', '4 x 75 ml', '20 bags, 40 g Net.',
       '12 x 355 ml', '1.47 kg', '397 g', '142 g', '750 g', '515 g',
       '12 x 75 ml', '4 x 100 ml', '4 x 99 g', '525 g', '540ml', '250ml',
       '600 g', '428 mL', '946ml', '6 x 35 g', '1pcs', '430 mL', '213 mL',
       '228 g', '616 g', '794g', '284 g', '24', '678 g', '12 x 355 mL',
       '4 x 57 g', '125g', '768 g', '736 g', '600 mL', '4 x 60 g',
       '8 x 113 g', '340 g; 12 oz', '6 x 142g', '908 grams', '680 g',
       '1.332 L', '4 x 170 g', '6 x 55 ml', '6 x 25 g',
       '12 x 355 mL CANS'], dtype=object)